main: org.delaware.Main
version: 1.8.0
name: DBFuture
author: DelawareX
depend: [WorldEdit,WorldGuard,Factions,MassiveCore,ProtocolLib]
softdepend:
  - Essentials

overridden-commands:
  - nick
  - nickname